/**
 * finplan-ai.js
 *
 * Generates focused, section-specific AI context markdown for the FinPlan UI.
 * Each section produces a self-contained summary with directional references
 * to adjacent sections for broader or deeper context.
 */

import { InstrumentMeta, InstrumentType } from '../instruments/instrument.js';
import { classifyAssetGroup, AssetGroupMeta } from '../asset-groups.js';
import { Metric, MetricLabel } from '../metric.js';
import {
    global_user_startAge, global_user_retirementAge, global_user_finishAge,
    global_filingAs, global_inflationRate, global_backtestYear,
} from '../globals.js';
import { getMonteCarloResults } from '../monte-carlo.js';
import { getGuardrailsResults } from '../guardrails.js';

const fmt = (val) =>
    new Intl.NumberFormat('en-US', {
        style: 'currency', currency: 'USD', maximumFractionDigits: 0,
    }).format(val || 0);

const pct = (val, decimals = 1) => (val * 100).toFixed(decimals) + '%';

const GENERATOR_LINE = '\n---\n*Generated by https://Charting.Finance/ portfolio simulator*\n';

// ── Section ordering for directional references ──────────────────

const SECTIONS = [
    { key: 'timeline',    label: 'Your Timeline' },
    { key: 'portfolio',   label: 'Your Portfolio' },
    { key: 'projections', label: 'Projections' },
    { key: 'simulations', label: 'Simulations' },
    { key: 'details',     label: 'Details' },
    { key: 'spreadsheet', label: 'Spreadsheet' },
];

function directionalNotes(sectionKey) {
    const idx = SECTIONS.findIndex(s => s.key === sectionKey);
    let md = '';

    if (idx > 0) {
        const above = SECTIONS.slice(0, idx).map(s => `**${s.label}**`);
        md += `> For broader context, refer to: ${above.join(', ')} (above this section).\n\n`;
    }
    if (idx < SECTIONS.length - 1) {
        const below = SECTIONS.slice(idx + 1).map(s => `**${s.label}**`);
        md += `> For more detailed data, refer to: ${below.join(', ')} (below this section).\n\n`;
    }

    return md;
}

// ── Timeline ────────────────────────────────────────────────────

export function generateTimelineMarkdown(portfolio, lifeEvents) {
    let md = `# Your Timeline\n\n`;
    md += `This section shows the user's life phases and financial timeline.\n\n`;

    md += `## Lifecycle\n`;
    md += `| Parameter | Value |\n`;
    md += `| :--- | :--- |\n`;
    md += `| Current Age | ${global_user_startAge} |\n`;
    md += `| Retirement Age | ${global_user_retirementAge} |\n`;
    md += `| Plan Through Age | ${global_user_finishAge} |\n`;
    md += `| Filing Status | ${global_filingAs} |\n`;
    md += `| Inflation Rate | ${pct(global_inflationRate)} |\n`;
    if (global_backtestYear && global_backtestYear !== 'current') {
        md += `| Backtest From | ${global_backtestYear} |\n`;
    }
    md += '\n';

    if (portfolio) {
        md += `## Simulation Span\n`;
        md += `${portfolio.firstDateInt.toString()} to ${portfolio.lastDateInt.toString()}\n\n`;
    }

    if (lifeEvents?.length > 0) {
        md += `## Life Events / Phases\n`;
        for (const ev of lifeEvents) {
            md += `- **${ev.type}** at ${ev.triggerDateInt.toString()}`;
            if (ev.displayName) md += ` — ${ev.displayName}`;
            md += '\n';
        }
        md += '\n';
    }

    md += directionalNotes('timeline');
    md += GENERATOR_LINE;
    return md;
}

// ── Portfolio ───────────────────────────────────────────────────

export function generatePortfolioSectionMarkdown(portfolio) {
    if (!portfolio) return `# Your Portfolio\n\nNo simulation has been run yet.\n` + GENERATOR_LINE;

    const assets = portfolio.modelAssets;
    let md = `# Your Portfolio\n\n`;
    md += `This section shows all financial assets grouped by category, with current values at the selected date.\n\n`;

    // Net worth
    const startNW = portfolio.startValue().amount;
    const endNW = portfolio.finishValue().amount;
    md += `## Net Worth\n`;
    md += `| Metric | Value |\n`;
    md += `| :--- | ---: |\n`;
    md += `| Starting | ${fmt(startNW)} |\n`;
    md += `| Ending | ${fmt(endNW)} |\n`;
    md += `| Change | ${fmt(endNW - startNW)} |\n\n`;

    // Group-level summary
    md += `## Assets by Group\n`;
    const groups = new Map();
    for (const a of assets) {
        const gk = classifyAssetGroup(a.instrument);
        if (!groups.has(gk)) groups.set(gk, []);
        groups.get(gk).push(a);
    }

    for (const [gk, gassets] of groups) {
        const meta = AssetGroupMeta.get(gk);
        if (!meta) continue;
        md += `### ${meta.groupEmoji} ${meta.label}\n`;
        for (const a of gassets) {
            const ameta = InstrumentMeta.get(a.instrument);
            const val = a.finishCurrency?.amount ?? a.startCurrency?.amount ?? 0;
            const status = a.isClosed ? ' (closed)' : '';
            md += `- **${a.displayName}** (${ameta?.label || a.instrument}): ${fmt(val)}${status}\n`;
        }
        md += '\n';
    }

    // Fund transfer topology
    const hasTransfers = assets.some(a => a.fundTransfers?.length > 0);
    if (hasTransfers) {
        md += `## Fund Transfer Topology\n`;
        for (const a of assets) {
            if (!a.fundTransfers?.length) continue;
            for (const ft of a.fundTransfers) {
                const parts = [];
                if (ft.monthlyMoveValue > 0) parts.push(`${ft.monthlyMoveValue}% monthly`);
                if (ft.closeMoveValue > 0) parts.push(`${ft.closeMoveValue}% on close`);
                md += `- ${a.displayName} → ${ft.toDisplayName} (${parts.join(', ')})\n`;
            }
        }
        md += '\n';
    }

    md += directionalNotes('portfolio');
    md += GENERATOR_LINE;
    return md;
}

// ── Projections ─────────────────────────────────────────────────

export function generateProjectionsSectionMarkdown(portfolio, metricName) {
    if (!portfolio) return `# Projections\n\nNo simulation has been run yet.\n` + GENERATOR_LINE;

    const label = MetricLabel[metricName] || metricName;
    let md = `# Projections — ${label}\n\n`;
    md += `This section shows macro (grouped) and micro (individual asset) projections for the selected metric.\n\n`;

    const assets = portfolio.modelAssets.filter(a => {
        const h = a.getHistory(metricName);
        return h && h.length > 0 && h.some(v => v !== 0);
    });

    if (assets.length === 0) {
        md += `No assets track the **${label}** metric.\n\n`;
        md += directionalNotes('projections');
        md += GENERATOR_LINE;
        return md;
    }

    md += `**${assets.length} asset(s)** contribute: ${assets.map(a => a.displayName).join(', ')}.\n\n`;

    // Yearly snapshots
    const first = portfolio.firstDateInt;
    const isCumulative = metricName === Metric.VALUE || metricName === Metric.CASH_FLOW_ACCUMULATED;
    const rows = [];

    for (const asset of assets) {
        const history = asset.getHistory(metricName);
        if (!history) continue;
        let month = first.month, year = first.year, yearlySum = 0;
        for (let i = 0; i < history.length; i++) {
            const val = typeof history[i] === 'number' ? history[i] : (history[i]?.amount ?? 0);
            yearlySum = isCumulative ? val : yearlySum + val;
            if (month === 12 || i === history.length - 1) {
                let row = rows.find(r => r.year === year);
                if (!row) { row = { year, values: {} }; rows.push(row); }
                row.values[asset.displayName] = yearlySum;
                yearlySum = 0;
            }
            month++;
            if (month > 12) { month = 1; year++; }
        }
    }
    rows.sort((a, b) => a.year - b.year);

    if (rows.length > 0) {
        md += `## Yearly ${label}\n`;
        md += `| Year | ${assets.map(a => a.displayName).join(' | ')} | Total |\n`;
        md += `| :--- | ${assets.map(() => '---:').join(' | ')} | ---: |\n`;
        for (const row of rows) {
            let total = 0;
            const cells = assets.map(a => {
                const v = row.values[a.displayName] ?? 0;
                total += v;
                return fmt(v);
            });
            md += `| ${row.year} | ${cells.join(' | ')} | ${fmt(total)} |\n`;
        }
        md += '\n';
    }

    md += directionalNotes('projections');
    md += GENERATOR_LINE;
    return md;
}

// ── Simulations ─────────────────────────────────────────────────

export function generateSimulationsSectionMarkdown(portfolio) {
    if (!portfolio) return `# Simulations\n\nNo simulation has been run yet.\n` + GENERATOR_LINE;

    let md = `# Simulations\n\n`;
    md += `This section covers Monte Carlo analysis and Guyton-Klinger guardrails — stress testing the portfolio under randomized historical returns.\n\n`;

    // Monte Carlo
    const mcResults = getMonteCarloResults();
    if (mcResults) {
        md += `## Monte Carlo Analysis\n`;
        md += `*${mcResults.numSimulations.toLocaleString()} simulations*`;
        if (mcResults.withGuardrails) md += ` *with guardrails active*`;
        md += '\n\n';

        const { bands, bandData, baselineData } = mcResults;
        const lastIdx = bandData[0].length - 1;
        const baselineEnd = baselineData[lastIdx];

        md += `| Percentile | Ending Value |\n`;
        md += `| :--- | ---: |\n`;
        for (let b = bands.length - 1; b >= 0; b--) {
            md += `| ${bands[b]}th | ${fmt(bandData[b][lastIdx])} |\n`;
        }
        md += `| **Baseline** | **${fmt(baselineEnd)}** |\n\n`;

        const p10 = bandData[0][lastIdx];
        const p90 = bandData[4][lastIdx];
        md += `10th–90th spread: ${fmt(p90 - p10)}. `;
        if (p10 < 0) md += `**Warning:** 10th percentile is negative (${fmt(p10)}).`;
        md += '\n\n';
    } else {
        md += `## Monte Carlo\nNot yet run. Click ▶ Run to generate.\n\n`;
    }

    // Guardrails
    const gr = getGuardrailsResults();
    if (gr) {
        md += `## Guardrails\n`;
        md += `Target withdrawal: ${gr.params.withdrawalRate}%, `;
        md += `preservation: ${gr.params.preservation}%, `;
        md += `prosperity: ${gr.params.prosperity}%, `;
        md += `adjustment: ±${gr.params.adjustment}%\n\n`;

        if (gr.events?.length > 0) {
            md += `| Year | Event | Rate → Adjusted |\n`;
            md += `| :--- | :--- | :--- |\n`;
            for (const evt of gr.events) {
                const label = evt.type === 'preservation' ? 'Cut' : 'Raise';
                md += `| ${evt.year} | ${label} | ${pct(evt.rate)} → ${pct(evt.adjustedTo)} |\n`;
            }
            md += '\n';
        } else {
            md += `No guardrail events triggered — withdrawal rate stayed within thresholds.\n\n`;
        }
    } else {
        md += `## Guardrails\nNot yet run. Click ▶ Run to generate.\n\n`;
    }

    md += directionalNotes('simulations');
    md += GENERATOR_LINE;
    return md;
}

// ── Details ─────────────────────────────────────────────────────

export function generateDetailsSectionMarkdown(portfolio) {
    if (!portfolio) return `# Details\n\nNo simulation has been run yet.\n` + GENERATOR_LINE;

    let md = `# Details\n\n`;
    md += `This section contains credit memos (audit trail of every value change) and financial reports (monthly/yearly income, taxes, expenses).\n\n`;

    // Credit memo summary by asset
    const memosByAsset = new Map();
    for (const a of portfolio.modelAssets) {
        if (!a.creditMemos?.length) continue;
        let total = 0;
        for (const m of a.creditMemos) total += m.amount?.amount ?? 0;
        memosByAsset.set(a.displayName, { count: a.creditMemos.length, total });
    }

    if (memosByAsset.size > 0) {
        md += `## Credit Memo Summary\n`;
        md += `| Asset | Memos | Net Amount |\n`;
        md += `| :--- | ---: | ---: |\n`;
        for (const [name, { count, total }] of memosByAsset) {
            md += `| ${name} | ${count} | ${fmt(total)} |\n`;
        }
        md += '\n';
    }

    // Tax summary from portfolio total
    const total = portfolio.total;
    if (total) {
        md += `## Lifetime Tax Summary\n`;
        md += `| Category | Amount |\n`;
        md += `| :--- | ---: |\n`;
        md += `| Income Tax | ${fmt(Math.abs(total.incomeTax.amount))} |\n`;
        md += `| SS Tax | ${fmt(Math.abs(total.socialSecurityTax.amount))} |\n`;
        md += `| Medicare Tax | ${fmt(Math.abs(total.medicareTax.amount))} |\n`;
        md += `| LT Capital Gains Tax | ${fmt(Math.abs(total.longTermCapitalGainsTax.amount))} |\n`;
        md += `| Property Taxes | ${fmt(Math.abs(total.propertyTaxes.amount))} |\n`;
        md += `| **Total** | **${fmt(Math.abs(total.totalTaxes().amount))}** |\n\n`;
    }

    // Yearly cash flow from reports
    const yearlyReports = portfolio.generatedReports.filter(r => r.type === 'yearly');
    if (yearlyReports.length > 0) {
        md += `## Annual Cash Flow\n`;
        md += `| Year | Income | Taxes | Expenses | Cash Surplus |\n`;
        md += `| :--- | ---: | ---: | ---: | ---: |\n`;
        for (const report of yearlyReports) {
            const p = report.pkg;
            const income = p.totalIncome().amount;
            const taxes = Math.abs(p.totalTaxes().amount);
            const expenses = Math.abs(p.expense.amount);
            const surplus = income - taxes - expenses;
            md += `| ${report.dateLabel} | ${fmt(income)} | ${fmt(taxes)} | ${fmt(expenses)} | ${fmt(surplus)} |\n`;
        }
        md += '\n';
    }

    md += directionalNotes('details');
    md += GENERATOR_LINE;
    return md;
}

// ── Spreadsheet ─────────────────────────────────────────────────

export function generateSpreadsheetSectionMarkdown(portfolio) {
    if (!portfolio) return `# Spreadsheet\n\nNo simulation has been run yet.\n` + GENERATOR_LINE;

    let md = `# Spreadsheet\n\n`;
    md += `This section provides the full monthly metric data for every asset in tabular form — the most granular data available in the simulator.\n\n`;

    // Just key stats — the actual spreadsheet is too large for markdown
    const assets = portfolio.modelAssets;
    md += `## Asset Summary\n`;
    md += `| Asset | Type | Start | End | Start Value | End Value | Return |\n`;
    md += `| :--- | :--- | :--- | :--- | ---: | ---: | ---: |\n`;

    for (const a of assets) {
        const meta = InstrumentMeta.get(a.instrument);
        const sv = a.startCurrency?.amount ?? 0;
        const ev = a.finishCurrency?.amount ?? 0;
        md += `| ${a.displayName} | ${meta?.label || a.instrument} | ${a.startDateInt.toString()} | ${a.effectiveFinishDateInt.toString()} | ${fmt(sv)} | ${fmt(ev)} | ${pct(a.annualReturnRate.rate)} |\n`;
    }
    md += '\n';

    md += directionalNotes('spreadsheet');
    md += GENERATOR_LINE;
    return md;
}

// ── Combined report (for MCP server / external consumers) ───────

/**
 * Generates a single self-contained markdown report combining all sections.
 * Drop-in replacement for the old assets-ai.js generatePortfolioMarkdown.
 * @param {Portfolio} portfolio - A portfolio that has been through chronometer_run()
 * @returns {string} Full markdown report
 */
export function generatePortfolioMarkdown(portfolio) {
    return [
        generatePortfolioSectionMarkdown(portfolio),
        generateProjectionsSectionMarkdown(portfolio, 'value'),
        generateDetailsSectionMarkdown(portfolio),
        generateSpreadsheetSectionMarkdown(portfolio),
    ].join('\n\n');
}
