/**
 * projections-ai.js
 *
 * Generates Markdown reports for each projection tab, combining the
 * portfolio baseline with tab-specific analysis data.
 */

import { generatePortfolioMarkdown } from './assets-ai.js';

const fmt = (val) =>
    new Intl.NumberFormat('en-US', {
        style: 'currency', currency: 'USD', maximumFractionDigits: 0,
    }).format(val || 0);

const GENERATOR_LINE = '---\n*Generated by https://Charting.Finance/ portfolio simulator*\n';

/**
 * Strips the trailing generator line from the portfolio markdown
 * so tab-specific content can be appended before it.
 */
function baseMarkdown(portfolio) {
    let md = generatePortfolioMarkdown(portfolio);
    if (md.endsWith(GENERATOR_LINE)) {
        md = md.slice(0, -GENERATOR_LINE.length);
    }
    return md;
}

// ── Tab Dispatchers ─────────────────────────────────────────────

/**
 * @param {string} tabName - Active tab label text
 * @param {Portfolio} portfolio - Completed portfolio
 * @param {Object} context - Tab-specific data (mcResults, guardrailsData, etc.)
 * @returns {string} Markdown report
 */
export function generateProjectionsMarkdown(tabName, portfolio, context) {
    const tab = tabName.toLowerCase();

    if (tab.includes('monte carlo'))  return generateMonteCarloMarkdown(portfolio, context);
    if (tab.includes('guardrail'))    return generateGuardrailsMarkdown(portfolio, context);
    if (tab.includes('spreadsheet'))  return generateSpreadsheetMarkdown(portfolio);
    if (tab.includes('credit'))       return generateCreditMemosMarkdown(portfolio);
    if (tab.includes('report'))       return generateReportsMarkdown(portfolio);

    // Default: metrics chart tab (tab1)
    return generateMetricsMarkdown(portfolio);
}

// ── Metrics (Tab 1) ─────────────────────────────────────────────

function generateMetricsMarkdown(portfolio) {
    let md = baseMarkdown(portfolio);
    md += `---\n\n`;
    md += `# Metrics Projection\n\n`;
    md += `The metrics chart shows monthly time-series data for the selected metric across all portfolio assets. `;
    md += `Each asset's metric history is plotted independently, allowing comparison of growth trajectories, `;
    md += `income streams, and expense patterns over the simulation period.\n\n`;
    md += `*TODO: This section will include per-asset metric trajectories at yearly intervals.*\n\n`;
    md += GENERATOR_LINE;
    return md;
}

// ── Monte Carlo (Tab 2) ─────────────────────────────────────────

function generateMonteCarloMarkdown(portfolio, context) {
    const mcResults = context?.mcResults;
    if (!mcResults) {
        let md = baseMarkdown(portfolio);
        md += `---\n\n`;
        md += `# Monte Carlo Analysis\n\n`;
        md += `Monte Carlo has not been run yet. Open the Monte Carlo tab first, then try again.\n\n`;
        md += GENERATOR_LINE;
        return md;
    }

    let md = baseMarkdown(portfolio);
    md += `---\n\n`;
    md += `# Monte Carlo Analysis\n\n`;
    md += `*${mcResults.numSimulations.toLocaleString()} simulations using correlated historical returns (S&P 500, treasuries, CPI, wage growth)*`;
    if (mcResults.withGuardrails) md += ` *with Guyton-Klinger guardrails active*`;
    md += `\n\n`;

    const { bands, bandData, baselineData, labels } = mcResults;
    const lastIdx = bandData[0].length - 1;

    // Retirement phase callout
    if (mcResults.retirementDateInt) {
        const d = mcResults.retirementDateInt;
        md += `## Simulation Phases\n`;
        md += `The simulation uses a **two-phase model** anchored on the user's retirement date (${d.toString()}):\n\n`;
        md += `- **Accumulation Phase** (before ${d.toString()}): Asset returns use the user-specified deterministic rates.\n`;
        md += `- **Retirement / Withdrawal Phase** (${d.toString()} onward): Asset returns are randomized using correlated historical data (S&P 500, treasuries, CPI, wage growth), reflecting the uncertainty that matters most when drawing down assets.\n\n`;
    }

    // Terminal outcome distribution
    md += `## Terminal Portfolio Value Distribution\n`;
    md += `| Percentile | Ending Value | vs. Baseline |\n`;
    md += `| :--- | ---: | ---: |\n`;

    const baselineEnd = baselineData[baselineData.length - 1];

    for (let b = bands.length - 1; b >= 0; b--) {
        const val = bandData[b][lastIdx];
        const diff = val - baselineEnd;
        const sign = diff >= 0 ? '+' : '';
        md += `| ${bands[b]}th | ${fmt(val)} | ${sign}${fmt(diff)} |\n`;
    }

    md += `| **Baseline** | **${fmt(baselineEnd)}** | - |\n\n`;

    // Risk summary
    const p10 = bandData[0][lastIdx];
    const p90 = bandData[4][lastIdx];
    const median = bandData[2][lastIdx];
    const spread = p90 - p10;
    const downside = baselineEnd - p10;
    const upside = p90 - baselineEnd;

    md += `## Risk Summary\n`;
    md += `| Metric | Value |\n`;
    md += `| :--- | ---: |\n`;
    md += `| 10th–90th Spread | ${fmt(spread)} |\n`;
    md += `| Downside Risk (baseline to 10th) | ${fmt(downside)} |\n`;
    md += `| Upside Potential (baseline to 90th) | ${fmt(upside)} |\n`;
    md += `| Median vs Baseline | ${fmt(median - baselineEnd)} |\n\n`;

    // Yearly percentile trajectory
    md += `## Yearly Percentile Trajectory\n`;
    md += `| Date | 10th | 25th | Median | 75th | 90th | Baseline |\n`;
    md += `| :--- | ---: | ---: | ---: | ---: | ---: | ---: |\n`;

    for (let m = 0; m <= lastIdx; m++) {
        const label = labels[m];
        if (m === lastIdx || (label && label.startsWith('Jan'))) {
            md += `| ${label} | ${fmt(bandData[0][m])} | ${fmt(bandData[1][m])} | ${fmt(bandData[2][m])} | ${fmt(bandData[3][m])} | ${fmt(bandData[4][m])} | ${fmt(baselineData[m])} |\n`;
        }
    }
    md += '\n';

    // Observations
    const observations = [];

    if (p10 < 0) {
        observations.push(`The 10th percentile outcome is negative (${fmt(p10)}), indicating portfolio depletion in worst-case scenarios.`);
    }
    if (median > baselineEnd * 1.2) {
        observations.push(`The median outcome exceeds the baseline by more than 20%, suggesting the baseline assumptions may be conservative.`);
    } else if (median < baselineEnd * 0.8) {
        observations.push(`The median outcome is more than 20% below the baseline, suggesting the baseline return assumptions may be optimistic.`);
    }
    if (spread > baselineEnd * 2) {
        observations.push(`The 10th-to-90th percentile spread (${fmt(spread)}) is more than 2x the baseline ending value, indicating high outcome uncertainty.`);
    }
    if (downside > upside * 1.5) {
        observations.push(`Downside risk (${fmt(downside)}) significantly exceeds upside potential (${fmt(upside)}), suggesting an asymmetric risk profile.`);
    }

    if (observations.length > 0) {
        md += `## Monte Carlo Observations\n`;
        for (const obs of observations) {
            md += `- ${obs}\n`;
        }
        md += '\n';
    }

    md += GENERATOR_LINE;
    return md;
}

// ── Guardrails (Tab 3) ──────────────────────────────────────────

function generateGuardrailsMarkdown(portfolio, context) {
    const gr = context?.guardrailsResults;

    let md = baseMarkdown(portfolio);
    md += `---\n\n`;
    md += `# Guyton-Klinger Guardrails Analysis\n\n`;

    if (!gr) {
        md += `Guardrails simulation has not been run yet. Open the Guardrails tab first, then try again.\n\n`;
        md += GENERATOR_LINE;
        return md;
    }

    const { params, snapshots, events, labels, portfolioValues, withdrawalSteps } = gr;
    const pct = (v) => (v * 100).toFixed(1) + '%';

    // Retirement phase callout
    if (gr.retirementDateInt) {
        const d = gr.retirementDateInt;
        md += `## Simulation Phases\n`;
        md += `Guardrail adjustments (preservation cuts and prosperity raises) only activate after the user's retirement date (${d.toString()}):\n\n`;
        md += `- **Accumulation Phase** (before ${d.toString()}): Portfolio grows without guardrail intervention.\n`;
        md += `- **Retirement / Withdrawal Phase** (${d.toString()} onward): Guardrail thresholds are evaluated annually and adjustments applied when triggered.\n\n`;
    }

    // Parameters
    md += `## Guardrail Parameters\n`;
    md += `| Parameter | Value |\n`;
    md += `| :--- | :--- |\n`;
    md += `| Initial Withdrawal Rate | ${params.withdrawalRate}% |\n`;
    md += `| Preservation Threshold | ${params.preservation}% |\n`;
    md += `| Prosperity Threshold | ${params.prosperity}% |\n`;
    md += `| Adjustment Percentage | ±${params.adjustment}% |\n\n`;

    // Yearly snapshot table
    if (snapshots.length > 0) {
        md += `## Yearly Withdrawal Trajectory\n`;
        md += `| Year | Investable Assets | Annual Withdrawal | Withdrawal Rate |\n`;
        md += `| :--- | ---: | ---: | ---: |\n`;

        for (const snap of snapshots) {
            md += `| ${snap.year} | ${fmt(snap.investableAssets)} | ${fmt(snap.annualExpense)} | ${pct(snap.withdrawalRate)} |\n`;
        }
        md += '\n';
    }

    // Event timeline
    if (events.length > 0) {
        md += `## Guardrail Events\n`;
        md += `| Year | Event | Trigger Rate | Adjusted To |\n`;
        md += `| :--- | :--- | ---: | ---: |\n`;

        for (const evt of events) {
            const label = evt.type === 'preservation' ? 'Preservation Cut' : 'Prosperity Raise';
            md += `| ${evt.year} | ${label} | ${pct(evt.rate)} | ${pct(evt.adjustedTo)} |\n`;
        }
        md += '\n';
    } else {
        md += `## Guardrail Events\n`;
        md += `No guardrail events were triggered. The withdrawal rate stayed within the preservation and prosperity thresholds throughout the simulation.\n\n`;
    }

    // Portfolio value at yearly intervals
    md += `## Yearly Portfolio Value\n`;
    md += `| Date | Portfolio Value | Annual Withdrawal |\n`;
    md += `| :--- | ---: | ---: |\n`;

    const lastIdx = labels.length - 1;
    for (let m = 0; m <= lastIdx; m++) {
        const label = labels[m];
        if (m === lastIdx || (label && label.startsWith('Jan'))) {
            md += `| ${label} | ${fmt(portfolioValues[m])} | ${fmt(withdrawalSteps[m])} |\n`;
        }
    }
    md += '\n';

    // Observations
    const observations = [];

    const preservationEvents = events.filter(e => e.type === 'preservation');
    const prosperityEvents = events.filter(e => e.type === 'prosperity');

    if (preservationEvents.length > 0 && prosperityEvents.length === 0) {
        observations.push(`Only preservation cuts occurred (${preservationEvents.length} total), with no prosperity raises. The portfolio underperformed relative to the initial withdrawal rate.`);
    }
    if (prosperityEvents.length > preservationEvents.length) {
        observations.push(`More prosperity raises (${prosperityEvents.length}) than preservation cuts (${preservationEvents.length}), suggesting the portfolio generally outperformed expectations.`);
    }

    if (snapshots.length > 0) {
        const firstExpense = snapshots[0].annualExpense;
        const lastExpense = snapshots[snapshots.length - 1].annualExpense;
        const change = ((lastExpense / firstExpense) - 1) * 100;
        if (Math.abs(change) > 5) {
            const direction = change > 0 ? 'increased' : 'decreased';
            observations.push(`Annual withdrawal ${direction} by ${Math.abs(change).toFixed(0)}% over the simulation (${fmt(firstExpense)} to ${fmt(lastExpense)}).`);
        }
    }

    const endValue = portfolioValues[lastIdx];
    const startValue = portfolioValues[0];
    if (endValue < startValue * 0.5) {
        observations.push(`Portfolio value dropped to less than half its starting value, suggesting the withdrawal rate may not be sustainable.`);
    }

    if (observations.length > 0) {
        md += `## Guardrails Observations\n`;
        for (const obs of observations) {
            md += `- ${obs}\n`;
        }
        md += '\n';
    }

    md += GENERATOR_LINE;
    return md;
}

// ── Spreadsheet (Tab 4) ─────────────────────────────────────────

function generateSpreadsheetMarkdown(portfolio) {
    let md = baseMarkdown(portfolio);
    md += `---\n\n`;
    md += `# Spreadsheet Data Export\n\n`;
    md += `The spreadsheet view shows monthly metric values for every asset in a tabular format, `;
    md += `suitable for detailed inspection of individual months.\n\n`;
    md += `*TODO: This section will include a condensed version of the spreadsheet data at yearly intervals.*\n\n`;
    md += GENERATOR_LINE;
    return md;
}

// ── Credit Memos (Tab 5) ────────────────────────────────────────

function generateCreditMemosMarkdown(portfolio) {
    let md = baseMarkdown(portfolio);
    md += `---\n\n`;
    md += `# Credit Memo Audit Trail\n\n`;
    md += `Credit memos record every value change on every asset throughout the simulation — `;
    md += `deposits, withdrawals, growth, tax withholding, fund transfers, and more. `;
    md += `They form the complete audit trail of the simulation.\n\n`;
    md += `*TODO: This section will include a summary of credit memo activity by asset and category.*\n\n`;
    md += GENERATOR_LINE;
    return md;
}

// ── Reports (Tab 6) ─────────────────────────────────────────────

function generateReportsMarkdown(portfolio) {
    let md = baseMarkdown(portfolio);
    md += `---\n\n`;
    md += `# Financial Reports\n\n`;
    md += `The reports view shows monthly and yearly FinancialPackage snapshots — `;
    md += `detailed breakdowns of income, taxes, contributions, expenses, and cash flow `;
    md += `as computed by the simulation engine.\n\n`;
    md += `*TODO: This section will include the yearly FinancialPackage reports in markdown table format.*\n\n`;
    md += GENERATOR_LINE;
    return md;
}
